/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import entidades.Categorias;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import servicios.CategoriasService;

/**
 *
 * @author alvaro
 */
public class CategoryComponent extends javax.swing.JPanel {

    private Integer id;
    private String nombre;
    private Runnable onDeleteCallback;

    /**
     * Creates new form CategoryComponent
     */
    public CategoryComponent() {
        initComponents();
    }

    public CategoryComponent(Integer id, String nombre) {
        initComponents();
        this.id = id;
        this.nombre = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        categoryField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlShadow, 2));

        deleteBtn.setText("Eliminar");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        modifyBtn.setText("Modificar");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(modifyBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modifyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryField))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Deseas borrar la nota definitivamente?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );
        
        if (opcion == JOptionPane.YES_OPTION) {
            CategoriasService.borrarCategoriaPorId(id);

            if (onDeleteCallback != null) {
                onDeleteCallback.run(); // Trigger reload in dialog
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        // TODO add your handling code here:
        String nuevoNombre = this.categoryField.getText();
        if (!nuevoNombre.isBlank()) {
            Categorias nuevaCat = new Categorias(this.id);
            nuevaCat.setNombre(nuevoNombre);
            CategoriasService.modificarCategoriaPorId(nuevaCat);

            if (onDeleteCallback != null) {
                onDeleteCallback.run(); // Trigger reload in dialog
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error nombre de categoria vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton modifyBtn;
    // End of variables declaration//GEN-END:variables

    public Integer getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public JTextField getCategoryField() {
        return categoryField;
    }

    public void setCategoryField(JTextField categoryField) {
        this.categoryField = categoryField;
    }

    public Runnable getOnDeleteCallback() {
        return onDeleteCallback;
    }

    public void setOnDeleteCallback(Runnable onDeleteCallback) {
        this.onDeleteCallback = onDeleteCallback;
    }
}
